### ISSUE TITLE
Genotype-Phenotype data missing?

### ISSUE THREAD

**Issue by alartin** [mitchgill16/Soybean_Trait_Prediction#1]
Hi,
It looks like no genotype-phenotype data available such as SCC_Merged_filtered.csv_train_testQTL_SNPS.csv to reproduce the conclusion.

**Comment by mitchgill16** [comment]
> Hi, It looks like no genotype-phenotype data available such as SCC_Merged_filtered.csv_train_testQTL_SNPS.csv to reproduce the conclusion.

Hi, thanks for reading the paper and looking through the repository :) There is no datasets through the repository as the aim was to help researchers set up similar pipelines with their own data + the data is quite big. However, if you were after the raw dataset as used by us, the raw genotype data is available here: https://research-repository.uwa.edu.au/files/89232545/SNPs_lee.id.biallic_maf_0.05_geno_0.1.vcf.gz
Phenotype data for each soybean trait is available here: https://npgsweb.ars-grin.gov/
You'd just have to merge phenotype value to the genotype file by accession ID, and do all the cleaning and filtering as mentioned in the paper.

I understand that this probably a bit more data wrangling than you were after though, so I've managed to track down the processed datasets for the reduced SNPs :) 
https://www.dropbox.com/s/v0y5punfltlibk7/reduced_SNPs_dataset.zip?dl=0

The processed datasets for the full amount of SNPs are too big to download and upload all together so I have tried to make the storage link public: https://data.pawsey.org.au/public/?path=/NGS Analysis Results/shortTerm/mgill/DL/holdout_and_equivalent_merged_1pcnt_removed

If that doesn't work here is an example file for Seed Coat Colour to help you run through the notebooks.
https://www.dropbox.com/s/tel5eblgy89mneu/SCC_all_snps.zip?dl=0

Hopefully that is helpful for you :)
